// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRj0G4IH1cGk1XVmQTPt51DrFfld1PaDo',
    appId: '1:269693410993:web:7e23218ac8ec0a8f7a4c90',
    messagingSenderId: '269693410993',
    projectId: 'live-order-tracking',
    authDomain: 'live-order-tracking.firebaseapp.com',
    storageBucket: 'live-order-tracking.firebasestorage.app',
    measurementId: 'G-EELB98S919',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyxVejaeogVgTSjFz4rq-kiyJ8vn0BPI8',
    appId: '1:269693410993:android:8481312cc49fc53f7a4c90',
    messagingSenderId: '269693410993',
    projectId: 'live-order-tracking',
    storageBucket: 'live-order-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8aJHx2w61rsbB8zbpoBNthDFuJ1r-6U4',
    appId: '1:269693410993:ios:a852d4ac853e68937a4c90',
    messagingSenderId: '269693410993',
    projectId: 'live-order-tracking',
    storageBucket: 'live-order-tracking.firebasestorage.app',
    iosBundleId: 'com.example.liveOrderTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8aJHx2w61rsbB8zbpoBNthDFuJ1r-6U4',
    appId: '1:269693410993:ios:a852d4ac853e68937a4c90',
    messagingSenderId: '269693410993',
    projectId: 'live-order-tracking',
    storageBucket: 'live-order-tracking.firebasestorage.app',
    iosBundleId: 'com.example.liveOrderTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRj0G4IH1cGk1XVmQTPt51DrFfld1PaDo',
    appId: '1:269693410993:web:6aea24ad65059bca7a4c90',
    messagingSenderId: '269693410993',
    projectId: 'live-order-tracking',
    authDomain: 'live-order-tracking.firebaseapp.com',
    storageBucket: 'live-order-tracking.firebasestorage.app',
    measurementId: 'G-9RDYE52RRQ',
  );
}
